import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  X,
  Download,
  Copy,
  Check,
  Sparkles,
  Plus,
  Trash2,
  Eye,
  Code2,
  Smartphone,
  Globe,
  Layers,
  FileCode,
  RotateCcw,
  CheckCircle2,
  Play,
  Lock,
  Unlock,
  KeyRound,
  ShieldCheck,
  ShieldAlert,
  Delete
} from 'lucide-react';
import ProjectCard from './ProjectCard';
import ProjectModal from './ProjectModal';

const DEFAULT_PIN = "2026";

const DEFAULT_PROJECT = {
  id: "flutter-ecommerce-app",
  title: "Modern E-Commerce Mobile App",
  tagline: "High-performance shopping app with real-time checkout",
  category: "Flutter",
  order: 1,
  featured: true,
  flagship: false,
  mockup: "none",
  description: "Cross-platform mobile application featuring clean architecture, smooth micro-interactions, and instant cart sync.",
  image: "https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=1200&q=80",
  media: [
    {
      type: "image",
      url: "https://images.unsplash.com/photo-1556742049-0a67c5574f73?auto=format&fit=crop&w=1200&q=80",
      caption: "Storefront & Catalog Feed"
    },
    {
      type: "image",
      url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
      caption: "Real-time Cart and Checkout"
    }
  ],
  tech: ["Flutter", "Dart", "Bloc", "FastAPI", "PostgreSQL"],
  systemArchitecture: "Flutter App (Bloc) → FastAPI Server → PostgreSQL & Supabase",
  githubUrl: "https://github.com/laithmh",
  liveUrl: "",
  demoVideoUrl: "",
  caseStudy: {
    overview: "Engineered to deliver 60+ FPS performance on low-end devices with offline caching support and instant inventory updates.",
    keyFeatures: [
      "Offline-first architecture with local SQLite sync",
      "Event-driven state management with Bloc",
      "Stripe payment gateway integration",
      "Dark and Light dynamic themes"
    ],
    architecture: {
      pattern: "Clean Architecture (Data, Domain, Presentation)",
      stateManagement: "Bloc / Cubit with unidirectional data flow",
      backend: "FastAPI REST API with asynchronous PostgreSQL connectors",
      auth: "JWT token authentication with biometric refresh"
    },
    challengesAndSolutions: [
      {
        challenge: "Handling network dropouts during payment checkout.",
        solution: "Implemented idempotent API endpoints and local queue retry mechanisms."
      }
    ]
  }
};

const slugify = (text) => {
  return text
    .toString()
    .toLowerCase()
    .trim()
    .replace(/[\s\W-]+/g, '-')
    .replace(/^-+|-+$/g, '');
};

const generateJsContent = (project) => {
  return `/**
 * Project: ${project.title || 'Untitled Project'}
 * Generated by Portfolio Project Builder
 */

export default {
  id: ${JSON.stringify(project.id || 'my-project')},
  title: ${JSON.stringify(project.title || '')},
  tagline: ${JSON.stringify(project.tagline || '')},
  category: ${JSON.stringify(project.category || 'Flutter')},
  order: ${Number(project.order) || 1},
  featured: ${Boolean(project.featured)},
  flagship: ${Boolean(project.flagship)},
  mockup: ${JSON.stringify(project.mockup || 'none')},

  description: ${JSON.stringify(project.description || '')},

  image: ${JSON.stringify(project.image || '')},

  media: ${JSON.stringify(project.media || [], null, 4)},

  tech: ${JSON.stringify(project.tech || [], null, 4)},

  systemArchitecture: ${JSON.stringify(project.systemArchitecture || '')},

  githubUrl: ${JSON.stringify(project.githubUrl || '')},
  liveUrl: ${JSON.stringify(project.liveUrl || '')},
  demoVideoUrl: ${JSON.stringify(project.demoVideoUrl || '')},

  caseStudy: {
    overview: ${JSON.stringify(project.caseStudy?.overview || '')},
    keyFeatures: ${JSON.stringify(project.caseStudy?.keyFeatures || [], null, 6)},
    architecture: {
      pattern: ${JSON.stringify(project.caseStudy?.architecture?.pattern || '')},
      stateManagement: ${JSON.stringify(project.caseStudy?.architecture?.stateManagement || '')},
      backend: ${JSON.stringify(project.caseStudy?.architecture?.backend || '')},
      auth: ${JSON.stringify(project.caseStudy?.architecture?.auth || '')}
    },
    challengesAndSolutions: ${JSON.stringify(project.caseStudy?.challengesAndSolutions || [], null, 6)}
  }
};
`;
};

const ProjectBuilderModal = ({ isOpen, onClose }) => {
  const [isAuthenticated, setIsAuthenticated] = useState(() => {
    return sessionStorage.getItem('portfolio_admin_auth') === 'true';
  });
  const [pinInput, setPinInput] = useState('');
  const [pinError, setPinError] = useState(false);
  const [isChangingPin, setIsChangingPin] = useState(false);
  const [currentPinCheck, setCurrentPinCheck] = useState('');
  const [newPinCandidate, setNewPinCandidate] = useState('');
  const [changePinMsg, setChangePinMsg] = useState({ text: '', isError: false });

  const [project, setProject] = useState(DEFAULT_PROJECT);
  const [activeTab, setActiveTab] = useState('form'); // 'form' | 'preview' | 'code'
  const [techInput, setTechInput] = useState('');
  const [featureInput, setFeatureInput] = useState('');
  const [copied, setCopied] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const [previewModalOpen, setPreviewModalOpen] = useState(false);

  const getAdminPin = () => localStorage.getItem('portfolio_admin_pin') || DEFAULT_PIN;

  // Lock body scroll when modal is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
      setPinInput('');
      setPinError(false);
      setIsChangingPin(false);
    }
    return () => {
      document.body.style.overflow = '';
    };
  }, [isOpen]);

  // Physical keyboard listener for PIN entry
  useEffect(() => {
    if (!isOpen || isAuthenticated) return;

    const handleKeyDown = (e) => {
      if (e.key >= '0' && e.key <= '9') {
        handlePinDigit(e.key);
      } else if (e.key === 'Backspace') {
        handlePinBackspace();
      } else if (e.key === 'Escape') {
        onClose();
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, isAuthenticated, pinInput]);

  if (!isOpen) return null;

  const handlePinDigit = (digit) => {
    if (pinInput.length >= 4) return;
    const nextPin = pinInput + digit;
    setPinInput(nextPin);
    setPinError(false);

    if (nextPin.length === 4) {
      if (nextPin === getAdminPin()) {
        sessionStorage.setItem('portfolio_admin_auth', 'true');
        setTimeout(() => {
          setIsAuthenticated(true);
          setPinInput('');
        }, 180);
      } else {
        setPinError(true);
        setTimeout(() => {
          setPinInput('');
          setPinError(false);
        }, 700);
      }
    }
  };

  const handlePinBackspace = () => {
    setPinInput((prev) => prev.slice(0, -1));
    setPinError(false);
  };

  const handlePinClear = () => {
    setPinInput('');
    setPinError(false);
  };

  const handleLock = () => {
    sessionStorage.removeItem('portfolio_admin_auth');
    setIsAuthenticated(false);
    setPinInput('');
    onClose();
  };

  const handleChangePinSubmit = (e) => {
    e.preventDefault();
    if (currentPinCheck !== getAdminPin()) {
      setChangePinMsg({ text: 'Current PIN is incorrect', isError: true });
      return;
    }
    if (newPinCandidate.length !== 4 || !/^\d{4}$/.test(newPinCandidate)) {
      setChangePinMsg({ text: 'New PIN must be exactly 4 digits', isError: true });
      return;
    }
    localStorage.setItem('portfolio_admin_pin', newPinCandidate);
    setChangePinMsg({ text: 'PIN successfully changed!', isError: false });
    setTimeout(() => {
      setIsChangingPin(false);
      setCurrentPinCheck('');
      setNewPinCandidate('');
      setChangePinMsg({ text: '', isError: false });
    }, 1500);
  };

  // Auto-slugify ID when title changes
  const handleTitleChange = (newTitle) => {
    setProject((prev) => ({
      ...prev,
      title: newTitle,
      id: prev.id === slugify(prev.title) || !prev.id ? slugify(newTitle) : prev.id
    }));
  };

  const addTechTag = (tagToAdd) => {
    const tag = (tagToAdd || techInput).trim();
    if (tag && !project.tech.includes(tag)) {
      setProject((prev) => ({ ...prev, tech: [...prev.tech, tag] }));
      setTechInput('');
    }
  };

  const removeTechTag = (tagToRemove) => {
    setProject((prev) => ({
      ...prev,
      tech: prev.tech.filter((t) => t !== tagToRemove)
    }));
  };

  const addMediaItem = () => {
    setProject((prev) => ({
      ...prev,
      media: [
        ...prev.media,
        { type: 'image', url: '', caption: '' }
      ]
    }));
  };

  const updateMediaItem = (idx, field, value) => {
    setProject((prev) => {
      const updated = [...prev.media];
      updated[idx] = { ...updated[idx], [field]: value };
      return { ...prev, media: updated };
    });
  };

  const removeMediaItem = (idx) => {
    setProject((prev) => ({
      ...prev,
      media: prev.media.filter((_, i) => i !== idx)
    }));
  };

  const addFeature = () => {
    if (featureInput.trim()) {
      setProject((prev) => ({
        ...prev,
        caseStudy: {
          ...prev.caseStudy,
          keyFeatures: [...(prev.caseStudy?.keyFeatures || []), featureInput.trim()]
        }
      }));
      setFeatureInput('');
    }
  };

  const removeFeature = (idx) => {
    setProject((prev) => ({
      ...prev,
      caseStudy: {
        ...prev.caseStudy,
        keyFeatures: prev.caseStudy.keyFeatures.filter((_, i) => i !== idx)
      }
    }));
  };

  const handleCopyCode = () => {
    const code = generateJsContent(project);
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    const code = generateJsContent(project);
    const fileName = `${project.id || 'new-project'}.js`;
    const blob = new Blob([code], { type: 'application/javascript;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloaded(true);
    setTimeout(() => setDownloaded(false), 3000);
  };

  const jsCode = generateJsContent(project);

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-2 sm:p-4 md:p-6 overflow-y-auto">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="fixed inset-0 bg-black/75 backdrop-blur-md"
        />

        {/* 1. PIN CODE VERIFICATION SCREEN (IF NOT AUTHENTICATED) */}
        {!isAuthenticated ? (
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            transition={{ duration: 0.25 }}
            className="relative w-full max-w-sm bg-[#e0e5ec] dark:bg-[#161c26] text-gray-800 dark:text-gray-100 rounded-3xl p-6 sm:p-8 shadow-2xl z-10 border border-white/40 dark:border-gray-800 flex flex-col items-center"
          >
            <button
              onClick={onClose}
              className="absolute top-4 right-4 p-2 rounded-xl text-gray-500 hover:text-gray-900 dark:hover:text-white hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors"
            >
              <X size={18} />
            </button>

            {/* Shield Icon */}
            <div className={`w-16 h-16 rounded-2xl flex items-center justify-center mb-4 transition-colors ${
              pinError
                ? 'bg-red-500/10 text-red-500 animate-bounce'
                : 'bg-blue-500/10 text-blue-600 dark:text-blue-400'
            }`}>
              {pinError ? <ShieldAlert size={32} /> : <Lock size={30} />}
            </div>

            <h3 className="text-xl font-extrabold text-[#1a3a5f] dark:text-gray-100 mb-1">
              Admin Access Gate
            </h3>
            <p className="text-xs text-[#5d7d9e] dark:text-gray-400 text-center mb-6">
              Enter your 4-digit security PIN to unlock the Project Studio
            </p>

            {/* 4 PIN Dots */}
            <motion.div
              animate={pinError ? { x: [-10, 10, -10, 10, 0] } : {}}
              transition={{ duration: 0.3 }}
              className="flex items-center justify-center gap-4 mb-6"
            >
              {[0, 1, 2, 3].map((idx) => {
                const filled = pinInput.length > idx;
                return (
                  <div
                    key={idx}
                    className={`w-4 h-4 rounded-full border-2 transition-all duration-150 ${
                      pinError
                        ? 'border-red-500 bg-red-500'
                        : filled
                        ? 'border-blue-600 bg-blue-600 dark:border-blue-400 dark:bg-blue-400 scale-110 shadow-md'
                        : 'border-gray-400 dark:border-gray-600 bg-transparent'
                    }`}
                  />
                );
              })}
            </motion.div>

            {pinError && (
              <p className="text-xs text-red-500 font-bold mb-3">
                Incorrect PIN. Please try again.
              </p>
            )}

            {/* Keypad */}
            <div className="grid grid-cols-3 gap-3 w-full max-w-[240px]">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((num) => (
                <motion.button
                  key={num}
                  whileTap={{ scale: 0.92 }}
                  onClick={() => handlePinDigit(String(num))}
                  className="h-12 rounded-2xl bg-white dark:bg-gray-800 text-lg font-bold text-[#1a3a5f] dark:text-gray-100 shadow-neu-flat-sm dark:shadow-neu-dark-flat-sm hover:shadow-neu-pressed dark:hover:shadow-neu-dark-pressed transition-all"
                >
                  {num}
                </motion.button>
              ))}
              <motion.button
                whileTap={{ scale: 0.92 }}
                onClick={handlePinClear}
                className="h-12 rounded-2xl bg-transparent text-xs font-semibold text-gray-500 dark:text-gray-400 hover:text-red-500 transition-colors"
              >
                Clear
              </motion.button>
              <motion.button
                whileTap={{ scale: 0.92 }}
                onClick={() => handlePinDigit('0')}
                className="h-12 rounded-2xl bg-white dark:bg-gray-800 text-lg font-bold text-[#1a3a5f] dark:text-gray-100 shadow-neu-flat-sm dark:shadow-neu-dark-flat-sm hover:shadow-neu-pressed dark:hover:shadow-neu-dark-pressed transition-all"
              >
                0
              </motion.button>
              <motion.button
                whileTap={{ scale: 0.92 }}
                onClick={handlePinBackspace}
                className="h-12 rounded-2xl bg-transparent flex items-center justify-center text-gray-500 dark:text-gray-400 hover:text-red-500 transition-colors"
              >
                <Delete size={20} />
              </motion.button>
            </div>

            <p className="text-[11px] text-gray-400 dark:text-gray-500 mt-6 text-center">
              Default PIN is <code className="font-mono font-bold text-blue-500">{DEFAULT_PIN}</code>. You can customize it inside the studio.
            </p>
          </motion.div>
        ) : (
          /* 2. AUTHENTICATED PROJECT BUILDER STUDIO */
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 15 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 15 }}
            transition={{ duration: 0.25 }}
            className="relative w-full max-w-5xl h-[92vh] flex flex-col bg-[#e0e5ec] dark:bg-[#161c26] text-gray-800 dark:text-gray-100 rounded-3xl shadow-2xl overflow-hidden z-10 border border-white/40 dark:border-gray-800"
          >
            {/* Header */}
            <div className="flex items-center justify-between px-4 sm:px-6 py-3 sm:py-4 bg-[#e0e5ec]/95 dark:bg-[#161c26]/95 backdrop-blur border-b border-gray-300/40 dark:border-gray-800">
              <div className="flex items-center gap-2 sm:gap-3 min-w-0">
                <div className="p-2 rounded-xl bg-blue-500/10 text-blue-600 dark:text-blue-400 shrink-0">
                  <FileCode size={20} />
                </div>
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <h2 className="text-base sm:text-xl font-bold text-[#1a3a5f] dark:text-gray-100 truncate">
                      Project Studio
                    </h2>
                    <span className="hidden sm:inline-flex items-center gap-1 text-[11px] font-bold px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 shrink-0">
                      <ShieldCheck size={12} />
                      Admin
                    </span>
                  </div>
                  <p className="text-[11px] sm:text-xs text-[#5d7d9e] dark:text-gray-400 hidden sm:block">
                    Visually configure your project, test live preview, and download the <code className="text-blue-500 font-mono">.js</code> file
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-1.5 sm:gap-2 shrink-0">
                <button
                  onClick={() => setIsChangingPin(true)}
                  title="Change Security PIN"
                  className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors"
                >
                  <KeyRound size={13} />
                  Change PIN
                </button>
                <button
                  onClick={handleLock}
                  title="Lock Studio & Exit"
                  className="flex items-center gap-1 px-2.5 sm:px-3 py-1.5 rounded-xl text-xs font-semibold text-red-600 dark:text-red-400 hover:bg-red-100 dark:hover:bg-red-950/40 transition-colors"
                >
                  <Lock size={13} />
                  <span className="hidden sm:inline">Lock</span>
                </button>
                <button
                  onClick={onClose}
                  className="p-1.5 sm:p-2 rounded-xl text-gray-500 hover:text-gray-900 dark:hover:text-white hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors"
                >
                  <X size={20} />
                </button>
              </div>
            </div>

            {/* Navigation Bar (Tabs & Action Buttons) */}
            <div className="px-3 sm:px-6 py-2 sm:py-2.5 bg-gray-200/50 dark:bg-gray-900/40 border-b border-gray-300/30 dark:border-gray-800 flex flex-wrap items-center justify-between gap-2">
              {/* Tabs */}
              <div className="flex items-center gap-1 sm:gap-2 overflow-x-auto max-w-full">
                <button
                  onClick={() => setActiveTab('form')}
                  className={`flex items-center gap-1.5 px-3 sm:px-4 py-1.5 sm:py-2 rounded-xl text-xs font-bold whitespace-nowrap transition-all ${
                    activeTab === 'form'
                      ? 'bg-[#1a3a5f] text-white dark:bg-blue-600 shadow-sm'
                      : 'text-gray-600 dark:text-gray-400 hover:bg-gray-300/50 dark:hover:bg-gray-800'
                  }`}
                >
                  Details
                </button>
                <button
                  onClick={() => setActiveTab('preview')}
                  className={`flex items-center gap-1.5 px-3 sm:px-4 py-1.5 sm:py-2 rounded-xl text-xs font-bold whitespace-nowrap transition-all ${
                    activeTab === 'preview'
                      ? 'bg-[#1a3a5f] text-white dark:bg-blue-600 shadow-sm'
                      : 'text-gray-600 dark:text-gray-400 hover:bg-gray-300/50 dark:hover:bg-gray-800'
                  }`}
                >
                  <Eye size={14} />
                  Preview
                </button>
                <button
                  onClick={() => setActiveTab('code')}
                  className={`flex items-center gap-1.5 px-3 sm:px-4 py-1.5 sm:py-2 rounded-xl text-xs font-bold whitespace-nowrap transition-all ${
                    activeTab === 'code'
                      ? 'bg-[#1a3a5f] text-white dark:bg-blue-600 shadow-sm'
                      : 'text-gray-600 dark:text-gray-400 hover:bg-gray-300/50 dark:hover:bg-gray-800'
                  }`}
                >
                  <Code2 size={14} />
                  Code
                </button>
              </div>

              {/* Quick Export Actions */}
              <div className="flex items-center gap-1.5">
                <motion.button
                  whileHover={{ scale: 1.02 }}
                  whileTap={{ scale: 0.98 }}
                  onClick={handleCopyCode}
                  className="flex items-center gap-1 px-2.5 sm:px-3.5 py-1.5 rounded-xl bg-white dark:bg-gray-800 text-[#1a3a5f] dark:text-gray-200 text-xs font-bold shadow-sm hover:shadow transition-all"
                >
                  {copied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </motion.button>

                <motion.button
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={handleDownload}
                  className="flex items-center gap-1 px-3 sm:px-4 py-1.5 rounded-xl bg-[#1a3a5f] dark:bg-blue-600 text-white text-xs font-bold shadow-md hover:opacity-95 transition-all"
                >
                  <Download size={14} />
                  <span>Download .js</span>
                </motion.button>
              </div>
            </div>

            {/* Body Content */}
            <div className="flex-1 overflow-y-auto p-6">
              {/* TAB 1: FORM */}
              {activeTab === 'form' && (
                <div className="space-y-8 max-w-4xl mx-auto">
                  {/* Section 1: Basic Metadata */}
                  <div className="p-5 rounded-2xl bg-white/60 dark:bg-white/5 border border-gray-300/40 dark:border-gray-800 space-y-4 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-[#1a3a5f] dark:text-blue-400 flex items-center gap-2">
                      <Sparkles size={16} />
                      1. Basic Information
                    </h3>

                    <div className="grid sm:grid-cols-2 gap-4">
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Project Title *
                        </label>
                        <input
                          type="text"
                          value={project.title}
                          onChange={(e) => handleTitleChange(e.target.value)}
                          placeholder="e.g. HealthTrack AI"
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          File Slug / ID (e.g. <span className="font-mono text-blue-500">{project.id}.js</span>) *
                        </label>
                        <input
                          type="text"
                          value={project.id}
                          onChange={(e) => setProject({ ...project, id: slugify(e.target.value) })}
                          placeholder="e.g. health-track-ai"
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>
                    </div>

                    <div className="grid sm:grid-cols-3 gap-4">
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Category
                        </label>
                        <select
                          value={project.category}
                          onChange={(e) => setProject({ ...project, category: e.target.value })}
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        >
                          <option value="Flutter">Flutter</option>
                          <option value="Mobile">Mobile</option>
                          <option value="Web">Web</option>
                          <option value="Full-Stack">Full-Stack</option>
                          <option value="Backend">Backend</option>
                          <option value="UI/UX">UI/UX</option>
                        </select>
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Ordering Priority (1 = Top)
                        </label>
                        <input
                          type="number"
                          min="1"
                          max="99"
                          value={project.order}
                          onChange={(e) => setProject({ ...project, order: parseInt(e.target.value) || 1 })}
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Device Frame Mockup
                        </label>
                        <select
                          value={project.mockup || 'none'}
                          onChange={(e) => setProject({ ...project, mockup: e.target.value })}
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        >
                          <option value="none">Clean Frame (No Phone Mockup)</option>
                          <option value="phone">Smartphone Mockup Frame</option>
                        </select>
                      </div>
                    </div>

                    {/* Flag toggles */}
                    <div className="flex flex-wrap gap-6 pt-2">
                      <label className="flex items-center gap-2 cursor-pointer text-xs font-bold text-gray-700 dark:text-gray-300">
                        <input
                          type="checkbox"
                          checked={project.featured}
                          onChange={(e) => setProject({ ...project, featured: e.target.checked })}
                          className="w-4 h-4 rounded text-blue-600 focus:ring-blue-500"
                        />
                        <span>Featured Project (Adds Badge & Priority)</span>
                      </label>

                      <label className="flex items-center gap-2 cursor-pointer text-xs font-bold text-gray-700 dark:text-gray-300">
                        <input
                          type="checkbox"
                          checked={project.flagship}
                          onChange={(e) => setProject({ ...project, flagship: e.target.checked })}
                          className="w-4 h-4 rounded text-blue-600 focus:ring-blue-500"
                        />
                        <span>Flagship Spotlight (Shows at top of Projects section)</span>
                      </label>
                    </div>

                    <div>
                      <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                        Tagline / Subheading
                      </label>
                      <input
                        type="text"
                        value={project.tagline}
                        onChange={(e) => setProject({ ...project, tagline: e.target.value })}
                        placeholder="e.g. Cross-platform mobile ordering with real-time sync"
                        className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </div>

                    <div>
                      <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                        Card Description (Short summary for homepage card) *
                      </label>
                      <textarea
                        rows={2}
                        value={project.description}
                        onChange={(e) => setProject({ ...project, description: e.target.value })}
                        placeholder="Summary of features and user value..."
                        className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </div>
                  </div>

                  {/* Section 2: Media & Cover Image */}
                  <div className="p-5 rounded-2xl bg-white/60 dark:bg-white/5 border border-gray-300/40 dark:border-gray-800 space-y-4 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-[#1a3a5f] dark:text-blue-400 flex items-center gap-2">
                      <Globe size={16} />
                      2. Media & Screenshots
                    </h3>

                    <div>
                      <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                        Cover Thumbnail Image URL *
                      </label>
                      <input
                        type="text"
                        value={project.image}
                        onChange={(e) => setProject({ ...project, image: e.target.value })}
                        placeholder="https://images.unsplash.com/... or /my-screenshot.png"
                        className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono"
                      />
                    </div>

                    {/* Gallery Items */}
                    <div className="space-y-3">
                      <div className="flex items-center justify-between">
                        <label className="text-xs font-semibold text-gray-700 dark:text-gray-300">
                          Gallery Media ({project.media.length} items)
                        </label>
                        <button
                          onClick={addMediaItem}
                          className="inline-flex items-center gap-1 text-xs font-bold text-blue-600 dark:text-blue-400 hover:underline"
                        >
                          <Plus size={14} /> Add Slide / Video
                        </button>
                      </div>

                      {project.media.map((item, idx) => (
                        <div
                          key={idx}
                          className="flex flex-wrap sm:flex-nowrap items-center gap-2.5 p-2.5 rounded-xl bg-gray-100 dark:bg-gray-800/60 border border-gray-200 dark:border-gray-700"
                        >
                          <select
                            value={item.type}
                            onChange={(e) => updateMediaItem(idx, 'type', e.target.value)}
                            className="px-2.5 py-1.5 rounded-lg bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs"
                          >
                            <option value="image">Image</option>
                            <option value="video">Video (YouTube/Vimeo)</option>
                          </select>

                          <input
                            type="text"
                            value={item.url}
                            onChange={(e) => updateMediaItem(idx, 'url', e.target.value)}
                            placeholder={item.type === 'video' ? "YouTube / Vimeo URL" : "Image URL"}
                            className="flex-1 min-w-[200px] px-2.5 py-1.5 rounded-lg bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs font-mono"
                          />

                          <input
                            type="text"
                            value={item.caption}
                            onChange={(e) => updateMediaItem(idx, 'caption', e.target.value)}
                            placeholder="Slide Caption"
                            className="w-48 px-2.5 py-1.5 rounded-lg bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs"
                          />

                          <button
                            onClick={() => removeMediaItem(idx)}
                            className="p-1.5 text-red-500 hover:bg-red-50 dark:hover:bg-red-950/40 rounded-lg transition-colors"
                            title="Remove Slide"
                          >
                            <Trash2 size={14} />
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Section 3: Tech Stack & System Architecture */}
                  <div className="p-5 rounded-2xl bg-white/60 dark:bg-white/5 border border-gray-300/40 dark:border-gray-800 space-y-4 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-[#1a3a5f] dark:text-blue-400 flex items-center gap-2">
                      <Layers size={16} />
                      3. Tech Stack & Architecture Flow
                    </h3>

                    <div>
                      <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                        Technologies & Libraries
                      </label>
                      <div className="flex gap-2 mb-2">
                        <input
                          type="text"
                          value={techInput}
                          onChange={(e) => setTechInput(e.target.value)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                              e.preventDefault();
                              addTechTag();
                            }
                          }}
                          placeholder="Type technology (e.g. Flutter, Bloc, FastAPI) and press Add or Enter..."
                          className="flex-1 px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                        <button
                          onClick={() => addTechTag()}
                          className="px-4 py-2 rounded-xl bg-[#1a3a5f] dark:bg-blue-600 text-white text-xs font-bold"
                        >
                          Add Tag
                        </button>
                      </div>

                      {/* Quick suggestion pills */}
                      <div className="flex flex-wrap items-center gap-1.5 mb-3 text-xs text-gray-500">
                        <span className="text-[11px] font-semibold mr-1">Quick Add:</span>
                        {['Flutter', 'Dart', 'Bloc', 'GetX', 'FastAPI', 'PostgreSQL', 'Supabase', 'Firebase', 'React', 'Tailwind CSS'].map((tech) => (
                          <button
                            key={tech}
                            onClick={() => addTechTag(tech)}
                            disabled={project.tech.includes(tech)}
                            className="px-2 py-0.5 rounded-md bg-gray-200 dark:bg-gray-800 hover:bg-blue-100 dark:hover:bg-blue-900/40 text-[11px] font-medium disabled:opacity-40 transition-colors"
                          >
                            + {tech}
                          </button>
                        ))}
                      </div>

                      {/* Selected Tech Tags */}
                      <div className="flex flex-wrap gap-2">
                        {project.tech.map((t) => (
                          <span
                            key={t}
                            className="inline-flex items-center gap-1 px-3 py-1 rounded-lg bg-blue-100 dark:bg-blue-950/60 text-blue-700 dark:text-blue-300 text-xs font-semibold"
                          >
                            {t}
                            <button
                              onClick={() => removeTechTag(t)}
                              className="hover:text-red-500"
                            >
                              <X size={12} />
                            </button>
                          </span>
                        ))}
                      </div>
                    </div>

                    <div>
                      <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                        System Architecture Pipeline String
                      </label>
                      <input
                        type="text"
                        value={project.systemArchitecture}
                        onChange={(e) => setProject({ ...project, systemArchitecture: e.target.value })}
                        placeholder="e.g. Flutter Client (Bloc) → FastAPI Server → PostgreSQL & Redis"
                        className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm font-mono focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </div>
                  </div>

                  {/* Section 4: External Links */}
                  <div className="p-5 rounded-2xl bg-white/60 dark:bg-white/5 border border-gray-300/40 dark:border-gray-800 space-y-4 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-[#1a3a5f] dark:text-blue-400 flex items-center gap-2">
                      <Globe size={16} />
                      4. External Links
                    </h3>

                    <div className="grid sm:grid-cols-3 gap-4">
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          GitHub Repository URL
                        </label>
                        <input
                          type="text"
                          value={project.githubUrl}
                          onChange={(e) => setProject({ ...project, githubUrl: e.target.value })}
                          placeholder="https://github.com/laithmh/..."
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Live Demo / Store URL
                        </label>
                        <input
                          type="text"
                          value={project.liveUrl}
                          onChange={(e) => setProject({ ...project, liveUrl: e.target.value })}
                          placeholder="https://play.google.com/... or web URL"
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Demo Video URL (Optional)
                        </label>
                        <input
                          type="text"
                          value={project.demoVideoUrl}
                          onChange={(e) => setProject({ ...project, demoVideoUrl: e.target.value })}
                          placeholder="https://youtube.com/..."
                          className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                        />
                      </div>
                    </div>
                  </div>

                  {/* Section 5: Case Study Deep-Dive */}
                  <div className="p-5 rounded-2xl bg-white/60 dark:bg-white/5 border border-gray-300/40 dark:border-gray-800 space-y-4 shadow-sm">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-[#1a3a5f] dark:text-blue-400 flex items-center gap-2">
                      <Sparkles size={16} />
                      5. Case Study & Architecture Overview
                    </h3>

                    <div>
                      <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                        Case Study Overview (Shown inside Modal)
                      </label>
                      <textarea
                        rows={3}
                        value={project.caseStudy?.overview || ''}
                        onChange={(e) =>
                          setProject({
                            ...project,
                            caseStudy: { ...project.caseStudy, overview: e.target.value }
                          })
                        }
                        placeholder="Detailed engineering problem statement and impact..."
                        className="w-full px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </div>

                    {/* Key Features list */}
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-xs font-semibold text-gray-700 dark:text-gray-300">
                          Key Features ({project.caseStudy?.keyFeatures?.length || 0})
                        </label>
                      </div>
                      <div className="flex gap-2 mb-2">
                        <input
                          type="text"
                          value={featureInput}
                          onChange={(e) => setFeatureInput(e.target.value)}
                          onKeyDown={(e) => {
                            if (e.key === 'Enter') {
                              e.preventDefault();
                              addFeature();
                            }
                          }}
                          placeholder="Add key feature bullet point..."
                          className="flex-1 px-3.5 py-2 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm"
                        />
                        <button
                          onClick={addFeature}
                          className="px-4 py-2 rounded-xl bg-[#1a3a5f] dark:bg-blue-600 text-white text-xs font-bold"
                        >
                          Add Feature
                        </button>
                      </div>

                      <div className="space-y-1.5">
                        {project.caseStudy?.keyFeatures?.map((f, idx) => (
                          <div
                            key={idx}
                            className="flex items-center justify-between px-3 py-1.5 rounded-lg bg-gray-100 dark:bg-gray-800 text-xs"
                          >
                            <span className="flex-1 text-gray-700 dark:text-gray-200">• {f}</span>
                            <button
                              onClick={() => removeFeature(idx)}
                              className="text-gray-400 hover:text-red-500 ml-2"
                            >
                              <X size={13} />
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Architecture Pillars */}
                    <div className="grid sm:grid-cols-2 gap-3 pt-2">
                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Architecture Pattern
                        </label>
                        <input
                          type="text"
                          value={project.caseStudy?.architecture?.pattern || ''}
                          onChange={(e) =>
                            setProject({
                              ...project,
                              caseStudy: {
                                ...project.caseStudy,
                                architecture: {
                                  ...project.caseStudy?.architecture,
                                  pattern: e.target.value
                                }
                              }
                            })
                          }
                          placeholder="Clean Architecture (Presentation, Domain, Data)"
                          className="w-full px-3 py-1.5 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          State Management Strategy
                        </label>
                        <input
                          type="text"
                          value={project.caseStudy?.architecture?.stateManagement || ''}
                          onChange={(e) =>
                            setProject({
                              ...project,
                              caseStudy: {
                                ...project.caseStudy,
                                architecture: {
                                  ...project.caseStudy?.architecture,
                                  stateManagement: e.target.value
                                }
                              }
                            })
                          }
                          placeholder="Bloc with reactive event streaming"
                          className="w-full px-3 py-1.5 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Backend & Database Infrastructure
                        </label>
                        <input
                          type="text"
                          value={project.caseStudy?.architecture?.backend || ''}
                          onChange={(e) =>
                            setProject({
                              ...project,
                              caseStudy: {
                                ...project.caseStudy,
                                architecture: {
                                  ...project.caseStudy?.architecture,
                                  backend: e.target.value
                                }
                              }
                            })
                          }
                          placeholder="FastAPI Async REST API + PostgreSQL"
                          className="w-full px-3 py-1.5 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs"
                        />
                      </div>

                      <div>
                        <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                          Authentication & Security
                        </label>
                        <input
                          type="text"
                          value={project.caseStudy?.architecture?.auth || ''}
                          onChange={(e) =>
                            setProject({
                              ...project,
                              caseStudy: {
                                ...project.caseStudy,
                                architecture: {
                                  ...project.caseStudy?.architecture,
                                  auth: e.target.value
                                }
                              }
                            })
                          }
                          placeholder="JWT tokens with biometric refresh"
                          className="w-full px-3 py-1.5 rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-xs"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              )}

              {/* TAB 2: LIVE PREVIEW */}
              {activeTab === 'preview' && (
                <div className="space-y-8 max-w-2xl mx-auto py-4">
                  <div className="text-center space-y-1">
                    <span className="text-xs font-bold uppercase tracking-wider text-blue-600 dark:text-blue-400">
                      Real-Time Component Preview
                    </span>
                    <h3 className="text-xl font-bold text-[#1a3a5f] dark:text-gray-100">
                      Homepage Project Card
                    </h3>
                    <p className="text-xs text-[#5d7d9e] dark:text-gray-400">
                      Click the card or the button below to test the interactive Recruiter Case Study Modal.
                    </p>
                  </div>

                  {/* Rendered Card */}
                  <div className="max-w-md mx-auto">
                    <ProjectCard
                      project={project}
                      onSelect={() => setPreviewModalOpen(true)}
                    />
                  </div>

                  <div className="text-center pt-2">
                    <motion.button
                      whileHover={{ scale: 1.04 }}
                      whileTap={{ scale: 0.96 }}
                      onClick={() => setPreviewModalOpen(true)}
                      className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#1a3a5f] dark:bg-blue-600 text-white text-sm font-bold shadow-md hover:opacity-95 transition-all"
                    >
                      <Eye size={16} />
                      Test Full Case Study Modal
                    </motion.button>
                  </div>
                </div>
              )}

              {/* TAB 3: GENERATED CODE */}
              {activeTab === 'code' && (
                <div className="space-y-4 max-w-4xl mx-auto">
                  <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-2xl bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900/60">
                    <div>
                      <h4 className="text-sm font-bold text-blue-900 dark:text-blue-300">
                        Step 1: Download or Copy the file
                      </h4>
                      <p className="text-xs text-blue-700 dark:text-blue-400">
                        Save as <code className="bg-blue-100 dark:bg-blue-900 px-1.5 py-0.5 rounded font-mono font-bold">src/data/projects/{project.id || 'new-project'}.js</code>
                      </p>
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        onClick={handleCopyCode}
                        className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white dark:bg-gray-800 text-xs font-bold text-[#1a3a5f] dark:text-gray-200 shadow-sm"
                      >
                        {copied ? <Check size={14} className="text-emerald-500" /> : <Copy size={14} />}
                        {copied ? 'Copied to Clipboard' : 'Copy Code'}
                      </button>
                      <button
                        onClick={handleDownload}
                        className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[#1a3a5f] dark:bg-blue-600 text-white text-xs font-bold shadow-md hover:opacity-95"
                      >
                        {downloaded ? <Check size={14} className="text-emerald-400" /> : <Download size={14} />}
                        {downloaded ? 'Downloaded!' : 'Download File'}
                      </button>
                    </div>
                  </div>

                  {/* Instructions */}
                  <div className="p-4 rounded-2xl bg-white/70 dark:bg-gray-900/60 border border-gray-300/40 dark:border-gray-800 text-xs space-y-2 text-gray-600 dark:text-gray-300">
                    <span className="font-bold text-[#1a3a5f] dark:text-blue-400 block">
                      How it gets into your live portfolio:
                    </span>
                    <ol className="list-decimal list-inside space-y-1">
                      <li>Click <strong>Download File</strong> (downloads <code className="font-mono text-blue-500">{project.id}.js</code>).</li>
                      <li>Move the downloaded file into your portfolio folder: <code className="font-mono text-blue-500">my_portfolio/src/data/projects/</code></li>
                      <li>Vite automatically detects it and displays it on your portfolio instantly!</li>
                      <li>To publish to GitHub Pages, simply run: <code className="font-mono bg-gray-200 dark:bg-gray-800 px-1.5 py-0.5 rounded">git add . && git commit -m "add project" && git push</code></li>
                    </ol>
                  </div>

                  {/* Preformatted Code View */}
                  <div className="relative rounded-2xl overflow-hidden bg-[#0d1117] border border-gray-800 shadow-2xl">
                    <div className="flex items-center justify-between px-4 py-2.5 bg-[#161b22] border-b border-gray-800 text-xs font-mono text-gray-400">
                      <span>src/data/projects/{project.id || 'new-project'}.js</span>
                      <button
                        onClick={handleCopyCode}
                        className="text-gray-400 hover:text-white transition-colors"
                      >
                        {copied ? 'Copied!' : 'Copy'}
                      </button>
                    </div>
                    <pre className="p-4 text-xs font-mono text-gray-200 overflow-x-auto leading-relaxed max-h-[500px]">
                      <code>{jsCode}</code>
                    </pre>
                  </div>
                </div>
              )}
            </div>
          </motion.div>
        )}
      </div>

      {/* Embedded Test Modal for Live Preview */}
      {previewModalOpen && (
        <ProjectModal
          project={project}
          onClose={() => setPreviewModalOpen(false)}
        />
      )}

      {/* Change PIN Dialog */}
      {isChangingPin && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
          <div className="relative w-full max-w-sm bg-[#e0e5ec] dark:bg-[#1c222d] rounded-2xl p-6 shadow-2xl border border-gray-300 dark:border-gray-700">
            <h4 className="text-lg font-bold text-[#1a3a5f] dark:text-gray-100 mb-2 flex items-center gap-2">
              <KeyRound size={18} />
              Change Admin PIN
            </h4>
            <p className="text-xs text-gray-600 dark:text-gray-400 mb-4">
              Enter your current 4-digit PIN and set your new 4-digit PIN.
            </p>

            <form onSubmit={handleChangePinSubmit} className="space-y-3">
              <div>
                <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                  Current PIN
                </label>
                <input
                  type="password"
                  maxLength={4}
                  value={currentPinCheck}
                  onChange={(e) => setCurrentPinCheck(e.target.value)}
                  placeholder="••••"
                  className="w-full px-3 py-1.5 text-center font-mono tracking-widest rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-semibold mb-1 text-gray-700 dark:text-gray-300">
                  New 4-Digit PIN
                </label>
                <input
                  type="password"
                  maxLength={4}
                  value={newPinCandidate}
                  onChange={(e) => setNewPinCandidate(e.target.value)}
                  placeholder="••••"
                  className="w-full px-3 py-1.5 text-center font-mono tracking-widest rounded-xl bg-white dark:bg-gray-900 border border-gray-300 dark:border-gray-700 text-sm"
                  required
                />
              </div>

              {changePinMsg.text && (
                <p className={`text-xs font-bold text-center ${changePinMsg.isError ? 'text-red-500' : 'text-emerald-500'}`}>
                  {changePinMsg.text}
                </p>
              )}

              <div className="flex items-center justify-end gap-2 pt-2">
                <button
                  type="button"
                  onClick={() => {
                    setIsChangingPin(false);
                    setChangePinMsg({ text: '', isError: false });
                  }}
                  className="px-3 py-1.5 text-xs font-semibold text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-800 rounded-lg"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 text-xs font-bold text-white bg-[#1a3a5f] dark:bg-blue-600 rounded-lg shadow-sm"
                >
                  Save New PIN
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default ProjectBuilderModal;
